FROM localstack/localstack

RUN apk add --no-cache \
        bash \
        bash-completion \
        python \
        py-pip

RUN pip3 install awscli-local

COPY some_file.csv .
COPY init.sh /docker-entrypoint-initaws.d/1.init.sh

